### ISSUE TITLE
File-based Encryption on CalyxOS or LineageOS unofficial EurekaROM

### ISSUE THREAD

**Issue by leo-lb** [eurekadevelopment/Eureka-Kernel-Exynos7885-Q-R-S#2]
Hello!

I just installed CalyxOS from https://eurekadevelopment.github.io/rom13.html on my A10 device, all works great (thank you), but I see that FBE is disabled.

Is there any way to enable it?

If not, what is the issue preventing from enabling? I can try work on the solution.

I am looking forward to a more "release quality" build of CalyxOS that has unofficial OTA and ADB disabled by default. For better security and privacy. The device may not reach official inclusion criteria but I am looking to make it the best possible for A10 nonetheless.

Thank you!

**Comment by leo-lb** [comment]
@TheLopeist Hello, I see you modified fstab in your [fork](https://github.com/TheLopeist/android_device_samsung_exynos7885/commit/2f7e33398ab730d304cc257fe42d7e4fdd187c06) with some more options, is that all it takes?

I read that the Eureka kernel disables some Samsung security options, what are these? Do they have anything to do with encryption?

Also the [official procedure](https://forum.xda-developers.com/t/recovery-official-twrp-3-6-x-for-galaxy-a10-exynos-series-sm-a105-4-january-2022.4212641/) for installing TWRP implies running a script that claims to disable dm-verity and forceencrypt which for development is good but for privacy and security not.

**Comment by TheLopeist** [comment]
@leo-lb Yes, I try to figure out how the encryption is working. I have some help from the chat-gpt and follow the instruction:
https://source.android.com/docs/security/features/encryption/file-based?hl=en#aosp-implementation-details
I'm stopping at the point integrating with keymaster, because i didnt find the right folder/files. I had to do some research first!
And they only deactivate know for the rooted-version of this kernel and the encryption... nothing else so far

**Comment by kevios12** [comment]
Hi, File-base Encryption will not work on our Samsung devices (exynos7885)... It's broken.
